server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis
mybatis:
  type-aliases-package: com.jack.chen.springbootmybatis.bean
  mapper-locations: classpath*:mapper/*.xml
